
#define KEY_NAME_LEN    4+1 // \0 at end
#define KEY_TYPE_LEN    4+1

typedef struct SMC_Key
{
    char key_name[KEY_NAME_LEN];
    char key_type[KEY_TYPE_LEN];
};

typedef struct SMC_Type_Nfo
{
    char key_type[KEY_TYPE_LEN];
    char key_data_len;
};

SMC_Key mba_smc_key[] = {
    { "#KEY", "ui32" },
    { "$Adr", "ui32" },
    { "$Num", "ui8 " },
    { "+LKS", "flag" },
    { "ACCL", "ui8 " },
    { "ACEN", "ui8 " },
    { "ACFP", "flag" },
    { "ACIC", "ui16" },
    { "ACID", "ch8*" },
    { "ACIN", "flag" },
    { "ACLM", "ui16" },
    { "ACdb", "flag" },
    { "ACdl", "ui16" },
    { "ACic", "ui8 " },
    { "ADC0", "ui16" },
    { "ADC1", "ui16" },
    { "ADC2", "ui16" },
    { "ADC3", "ui16" },
    { "ADC4", "ui16" },
    { "ADC5", "ui16" },
    { "ADC6", "ui16" },
    { "ADC7", "ui16" },
    { "ADC8", "ui16" },
    { "ADC9", "ui16" },
    { "ADCa", "ui16" },
    { "ADCb", "ui16" },
    { "ADCc", "ui16" },
    { "ADCd", "ui16" },
    { "ADCe", "ui16" },
    { "ADCf", "ui16" },
    { "ADCg", "ui16" },
    { "ADCh", "ui16" },
    { "ADCi", "ui16" },
    { "ADCj", "ui16" },
    { "ADCk", "ui16" },
    { "ADCl", "ui16" },
    { "ADCm", "ui16" },
    { "ADCn", "ui16" },
    { "AL! ", "ui16" },
    { "ALCD", "fp88" },
    { "ALI0", "{ali" },
    { "ALI1", "{ali" },
    { "ALP0", "{alp" },
    { "ALP1", "{alp" },
    { "ALRV", "ui16" },
    { "ALSC", "{alc" },
    { "ALSF", "fp1f" },
    { "ALSL", "ui16" },
    { "ALV0", "{alv" },
    { "ALV1", "{alv" },
    { "AUPO", "ui8 " },
    { "B0AC", "si16" },
    { "B0AV", "ui16" },
    { "B0Al", "ui16" },
    { "B0Am", "ui8 " },
    { "B0Ar", "ui8 " },
    { "B0As", "ui8 " },
    { "B0At", "ui16" },
    { "B0Au", "ui16" },
    { "B0BI", "hex_" },
    { "B0CT", "ui16" },
    { "B0FC", "ui16" },
    { "B0LI", "ui16" },
    { "B0OS", "hex_" },
    { "B0PS", "hex_" },
    { "B0RI", "ui16" },
    { "B0RM", "ui16" },
    { "B0St", "hex_" },
    { "B0TF", "ui16" },
    { "BALG", "ui8 " },
    { "BATP", "flag" },
    { "BBAD", "flag" },
    { "BBIF", "ui8 " },
    { "BBIN", "flag" },
    { "BC1V", "ui16" },
    { "BC2V", "ui16" },
    { "BCLM", "ui8 " },
    { "BCMV", "ui16" },
    { "BEMB", "flag" },
    { "BFCL", "ui8 " },
    { "BFCT", "ui16" },
    { "BFLO", "ui8 " },
    { "BIMX", "ui16" },
    { "BIPD", "ui16" },
    { "BITV", "ui16" },
    { "BLPT", "ch8*" },
    { "BNCM", "ui8 " },
    { "BNCR", "ui8 " },
    { "BNum", "ui8 " },
    { "BPII", "sp78" },
    { "BPIT", "sp78" },
    { "BRII", "sp78" },
    { "BRIT", "sp78" },
    { "BRLP", "ui16" },
    { "BROS", "ui16" },
    { "BRS0", "ui16" },
    { "BRSC", "ui16" },
    { "BRWK", "ui16" },
    { "BSAC", "hex_" },
    { "BSIn", "hex_" },
    { "BTIL", "ui16" },
    { "BTTI", "ui8 " },
    { "BTVI", "ui8 " },
    { "BTVR", "ui8 " },
    { "BTVT", "ui8 " },
    { "BWLM", "ui8 " },
    { "CHBI", "ui16" },
    { "CHBV", "ui16" },
    { "CHGC", "ui16" },
    { "CHGD", "flag" },
    { "CHGI", "ui16" },
    { "CHGV", "ui16" },
    { "CHII", "ui16" },
    { "CHLC", "ui8 " },
    { "CLK!", "ui8 " },
    { "CLKC", "{clc" },
    { "CLKH", "{clh" },
    { "CLKS", "fp1f" },
    { "CLKT", "ui32" },
    { "CLSD", "ui16" },
    { "CLWK", "ui16" },
    { "CRCF", "ui32" },
    { "DID0", "ui32" },
    { "DID1", "ui32" },
    { "DM0C", "ui8 " },
    { "DM0F", "ui8 " },
    { "DM0I", "{hdi" },
    { "DM0M", "ui8 " },
    { "DM0P", "ui8 " },
    { "DM0S", "ui8 " },
    { "DM0T", "hex_" },
    { "DM0b", "ui32" },
    { "DM0g", "ui32" },
    { "DM0h", "ui8 " },
    { "DMP!", "hex_" },
    { "DMS!", "hex_" },
    { "DPB0", "ui8 " },
    { "DPB1", "ui8 " },
    { "DPLM", "{lim" },
    { "DT0A", "sp78" },
    { "DT0B", "sp78" },
    { "DT0C", "sp78" },
    { "ECIP", "ch8*" },
    { "ECIT", "ui8 " },
    { "EECC", "ui32" },
    { "ENV0", "ui8 " },
    { "EPCA", "ui32" },
    { "EPCF", "flag" },
    { "EPCI", "ui32" },
    { "EPCV", "ui16" },
    { "EPMA", "ch8*" },
    { "EPMI", "ui8 " },
    { "EPUA", "ui32" },
    { "EPUF", "flag" },
    { "EPUI", "ui32" },
    { "EPUV", "ui16" },
    { "EVCT", "ui16" },
    { "EVHF", "ch8*" },
    { "EVMD", "ui32" },
    { "EVRD", "ch8*" },
    { "EVSL", "ui8 " },
    { "F0Ac", "fpe2" },
    { "F0ID", "{fds" },
    { "F0Mn", "fpe2" },
    { "F0Mt", "ui16" },
    { "F0Mx", "fpe2" },
    { "F0Tg", "fpe2" },
    { "FNum", "ui8 " },
    { "FPDc", "fp79" },
    { "FRmn", "ui16" },
    { "FRmp", "ui16" },
    { "FS! ", "ui16" },
    { "FSDc", "ui8 " },
    { "G3AO", "ui32" },
    { "G3WD", "flag" },
    { "HBKP", "ch8*" },
    { "HBKT", "ui32" },
    { "HD0F", "ui8 " },
    { "HD0I", "{hdi" },
    { "HD0M", "ui8 " },
    { "HD0T", "ui16" },
    { "HDBS", "ui8 " },
    { "HDST", "hex_" },
    { "HDSW", "hex_" },
    { "HT0A", "sp78" },
    { "HT0B", "sp78" },
    { "HT0C", "sp78" },
    { "IAPC", "sp5a" },
    { "IB0P", "sp5a" },
    { "IBLC", "sp5a" },
    { "IC0C", "sp78" },
    { "IC0R", "sp5a" },
    { "IC1C", "sp5a" },
    { "IC2C", "sp5a" },
    { "ID0R", "sp5a" },
    { "IHDC", "sp5a" },
    { "IM0R", "sp5a" },
    { "IN0C", "sp5a" },
    { "IO0R", "sp5a" },
    { "IPBR", "sp5a" },
    { "IR1C", "sp5a" },
    { "LAcN", "ui8 " },
    { "LAtN", "ui16" },
    { "LC2D", "ui16" },
    { "LC2E", "ui16" },
    { "LCCC", "ui8 " },
    { "LCCN", "ui8 " },
    { "LCCQ", "ui8 " },
    { "LCKA", "ui8 " },
    { "LCKN", "ui8 " },
    { "LCLD", "ui16" },
    { "LCLG", "ui8 " },
    { "LCSA", "ui8 " },
    { "LCTN", "ui8 " },
    { "LCTQ", "ui8 " },
    { "LDEN", "ui16" },
    { "LDI2", "ui8 " },
    { "LDKN", "ui8 " },
    { "LDLG", "ui8 " },
    { "LDS4", "ui8 " },
    { "LDSP", "flag" },
    { "LDT1", "ui8 " },
    { "LDT2", "ui16" },
    { "LDT4", "ui32" },
    { "LDTF", "ui16" },
    { "LDWE", "ui32" },
    { "LKSB", "{lkb" },
    { "LKSS", "{lks" },
    { "MACA", "ui32" },
    { "MACM", "flag" },
    { "MACR", "ch8*" },
    { "MSAL", "hex_" },
    { "MSAc", "fp88" },
    { "MSAf", "fp6a" },
    { "MSAg", "fp88" },
    { "MSAm", "fp88" },
    { "MSDW", "flag" },
    { "MSG3", "flag" },
    { "MSHT", "ui8 " },
    { "MSLB", "ui16" },
    { "MSLC", "ui8 " },
    { "MSLD", "ui8 " },
    { "MSLF", "ui8 " },
    { "MSLG", "ui8 " },
    { "MSLP", "ui8 " },
    { "MSLS", "ui8 " },
    { "MSLT", "fp88" },
    { "MSPA", "fp6a" },
    { "MSPB", "flag" },
    { "MSPC", "ui8 " },
    { "MSPI", "ui8 " },
    { "MSPM", "ui8 " },
    { "MSPS", "ui16" },
    { "MSPT", "ui8 " },
    { "MSQA", "flag" },
    { "MSQC", "ui8 " },
    { "MSQD", "si8 " },
    { "MSQF", "flag" },
    { "MSQL", "ui8 " },
    { "MSRC", "ui32" },
    { "MSSD", "si8 " },
    { "MSSF", "ui32" },
    { "MSSG", "ui32" },
    { "MSSP", "si8 " },
    { "MSSR", "flag" },
    { "MSSS", "{mss" },
    { "MSTC", "ui16" },
    { "MSTS", "ui8 " },
    { "MSTc", "ui8 " },
    { "MSTe", "ui8 " },
    { "MSTf", "ui8 " },
    { "MSTi", "ui8 " },
    { "MSTm", "ui8 " },
    { "MSWA", "fp6a" },
    { "MSWE", "ui8 " },
    { "MSWF", "ui16" },
    { "MSWO", "ui16" },
    { "MSWP", "ui8 " },
    { "MSWr", "ui8 " },
    { "MSXC", "ch8*" },
    { "MSXD", "ch8*" },
    { "MSXK", "ch8*" },
    { "MSXN", "ui8 " },
    { "MSXS", "ch8*" },
    { "MSXb", "ui8 " },
    { "MSXc", "ch8*" },
    { "MSXd", "ch8*" },
    { "MSXk", "ch8*" },
    { "MSXm", "ui16" },
    { "MSXn", "ui8 " },
    { "MSXs", "ui32" },
    { "MSa!", "hex_" },
    { "MSac", "ui8 " },
    { "MSaf", "ui8 " },
    { "MSag", "ui8 " },
    { "MSam", "ui8 " },
    { "MSap", "ui8 " },
    { "MSci", "ui8 " },
    { "MScr", "hex_" },
    { "MSii", "ui8 " },
    { "MSir", "hex_" },
    { "NACK", "ui8 " },
    { "NATJ", "ui8 " },
    { "NATi", "ui16" },
    { "NOPB", "ui8 " },
    { "NTOK", "ui8 " },
    { "ONMI", "ui8 " },
    { "PAPC", "sp78" },
    { "PBLC", "sp78" },
    { "PC0C", "sp78" },
    { "PC0R", "sp78" },
    { "PC1C", "sp78" },
    { "PC2C", "sp78" },
    { "PCLT", "sp78" },
    { "PCPC", "sp78" },
    { "PCPG", "sp78" },
    { "PCPT", "sp78" },
    { "PDTR", "sp78" },
    { "PHDC", "sp78" },
    { "PHPC", "sp78" },
    { "PM0R", "sp78" },
    { "PN0C", "sp78" },
    { "PO0R", "sp78" },
    { "PPBR", "sp78" },
    { "PR1C", "sp78" },
    { "PSTR", "sp78" },
    { "PTHC", "sp78" },
    { "PZ0R", "sp78" },
    { "RBr ", "ch8*" },
    { "REV ", "{rev" },
    { "RMde", "char" },
    { "RPlt", "ch8*" },
    { "RSvn", "ui32" },
    { "RVBF", "{rev" },
    { "RVCR", "{rev" },
    { "RVUF", "{rev" },
    { "SAS!", "hex_" },
    { "SBF ", "hex_" },
    { "SBFC", "flag" },
    { "SBFD", "hex_" },
    { "SBFE", "flag" },
    { "SBFL", "hex_" },
    { "SBFN", "hex_" },
    { "SBFU", "hex_" },
    { "SBFV", "hex_" },
    { "SBS!", "ui16" },
    { "SCIA", "ui16" },
    { "SCIB", "ui32" },
    { "SCII", "ui8 " },
    { "SCIL", "ui8 " },
    { "SCXC", "sp78" },
    { "SFBR", "ui8 " },
    { "SIS!", "hex_" },
    { "SMBC", "ch8*" },
    { "SMBG", "ui8 " },
    { "SMBR", "ch8*" },
    { "SMBS", "ch8*" },
    { "SMBW", "ch8*" },
    { "SPDO", "ui8 " },
    { "SPH0", "ui16" },
    { "SPHR", "ui32" },
    { "SPHS", "ui8 " },
    { "SPHT", "ui16" },
    { "SPHZ", "ui8 " },
    { "SPT!", "hex_" },
    { "SPU!", "hex_" },
    { "SPV!", "hex_" },
    { "SRS!", "hex_" },
    { "SWER", "hex_" },
    { "TB0T", "sp78" },
    { "TB1T", "sp78" },
    { "TB2T", "sp78" },
    { "TC0C", "sp78" },
    { "TC0D", "sp78" },
    { "TC0E", "sp78" },
    { "TC0F", "sp78" },
    { "TC0P", "sp78" },
    { "TC1C", "sp78" },
    { "TC2C", "sp78" },
    { "TCGC", "sp78" },
    { "TCSA", "sp78" },
    { "TCXC", "sp78" },
    { "TH0A", "sp78" },
    { "TH0B", "sp78" },
    { "TH0J", "sp78" },
    { "TH0O", "sp78" },
    { "TH0a", "sp78" },
    { "TH0b", "sp78" },
    { "TH0c", "sp78" },
    { "TH0o", "hex_" },
    { "TH0x", "sp78" },
    { "THSP", "sp78" },
    { "TM0P", "sp78" },
    { "TPCD", "sp78" },
    { "Ta0P", "sp78" },
    { "Th1H", "sp78" },
    { "Tm0P", "sp78" },
    { "Tm1P", "sp78" },
    { "Ts0P", "sp78" },
    { "Ts0S", "sp78" },
    { "UBDC", "flag" },
    { "UFIS", "ui32" },
    { "UPRC", "ui16" },
    { "UREV", "ui8 " },
    { "URPP", "ui32" },
    { "URWD", "ui32" },
    { "USR0", "ui32" },
    { "USR1", "ui32" },
    { "USR2", "ui32" },
    { "USR3", "ui32" },
    { "VC0C", "sp5a" },
    { "VC2C", "sp5a" },
    { "VD0R", "sp5a" },
    { "VN0C", "sp5a" },
    { "VP0R", "sp5a" },
    { "WCPD", "ui8 " },
    { "WCPW", "ui8 " },
    { "WKEN", "ui8 " },
    { "WKTP", "ui8 " },
    { "WOr0", "si8 " },
    { "WOw0", "si8 " },
    { "zDBG", "ui8 " },
    { "zDSF", "flag" },
    { "zRST", "ui8 " },
};

SMC_Type_Nfo mba_smc_type_nfo[] = {
    { "ui8 ", 1 },
    { "ui16", 2 },
    { "ui32", 4 },
    { "flag", 4 },
    { "fp88", 4 },
    { "sp78", 4 },
    { "ui32", 4 },
    { "hex_", 4 },
};
